### ISSUE TITLE
BinDiff wrapper script

### ISSUE THREAD

**Issue by JonathanGoikhman** [TakahiroHaruyama/ida_haru#1]
Hey, I saw in your blog that you have written a wrapper script for BinDiff. 
I didn't find him, and would like to ask if you could share him.
I'm currently working on a project and this is exactly what i'm looking for  :)
Thank you.

**Comment by TakahiroHaruyama** [comment]
I modified the script for BinDiff 5.0. But version 5.0 contains a bug not allowing to import an existing .BinExport file. That means you can't utilize generated .BinDiff and .BinExport to import name/comment. You can just check the whole binary / function similarities on the command line.

Are you still wanting to get the code?

**Comment by JonathanGoikhman** [comment]
Yes, the bug is not critical for me, I would be happy if you share the code. Thank you.

**Comment by TakahiroHaruyama** [comment]
https://github.com/TakahiroHaruyama/ida_haru/tree/master/bindiff
